// 错误常量

const NAME_OR_PASSWORD_IS_REQUIRE = "NAME_OR_PASSWORD_IS_REQUIRE";
const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
const USER_DOES_NOT_EXISTS = "USER_DOES_NOT_EXISTS";
const PASSWORD_ISINCORRENT = "PASSWORD_ISINCORRENT";
const UNAUTHORIZATION = "UNAUTHORIZATION";
const UNPERMISSION = "UNPERMISSION";

module.exports = {
  NAME_OR_PASSWORD_IS_REQUIRE,
  USER_ALREADY_EXISTS,
  USER_DOES_NOT_EXISTS,
  PASSWORD_ISINCORRENT,
  UNAUTHORIZATION,
  UNPERMISSION,
};
